# -*- mode: ruby -*-
# vi: set ft=ruby :

VAGRANTFILE_API_VERSION = 2

Vagrant.configure(VAGRANTFILE_API_VERSION) do |config|
    MACHINES = [{
        :groups => ["mesos", "zk"],
        :instances => 3,
        :box => "correcthorse/Centos-7.1",
        :memory => 2048,
        :cpus => 2
    }]

    inventory_groups = { "vagrant_all" => [] }

    config.ssh.insert_key = false

    MACHINES.each do |opts|
         opts[:groups].each do |group|
            inventory_groups[group] = []
         end

        (1..opts[:instances]).each do |i|
            name = opts[:groups].join("-") + "-" + i.to_s

            opts[:groups].each do |group|
                inventory_groups[group].push(name)
            end
            inventory_groups["vagrant_all"].push(name)

            config.vm.define name do |instance|
                instance.vm.hostname = name + ".vagrant.dev"
                instance.vm.box = opts[:box]
                instance.vm.box_url = opts[:box_url]
                instance.vm.network "private_network", type: "dhcp"

                instance.vm.box_download_insecure = true

                instance.vm.provider "virtualbox" do |vb|
                    vb.name = name
                    vb.memory = opts[:memory]
                    vb.cpus = opts[:cpus]
                end

                if opts == MACHINES.last && i == opts[:instances]
                    instance.vm.provision "ansible" do |ansible|
                        ansible.playbook = "provision.yml"
                        ansible.verbose = "v"
                        ansible.groups = inventory_groups
                        ansible.limit = "all"
                        ansible.extra_vars = {
                            default_iface: "enp0s8"
                        }
                    end
                end
            end
        end
    end
end
