# -*- mode: ruby -*-
# vi: set ft=ruby :

# All Vagrant configuration is done below. The "2" in Vagrant.configure
# configures the configuration version (we support older styles for
# backwards compatibility). Please don't change it unless you know what
# you're doing.
Vagrant.configure(2) do |config|
  config.vm.box = "centos/7"
#  config.proxy.http     = "http://userproxy.visa.com:80"
#  config.proxy.https    = "http://userproxy.visa.com:443"
#  config.proxy.no_proxy = "localhost,127.0.0.1,127.0.1.1,127.0.1.1*,local.home"
  
  config.vm.define "ntpd-machine1" do |machine|
    machine.vm.hostname = "ntpd-machine1"
    machine.vm.network :private_network, ip: "10.0.15.21"
    machine.vm.synced_folder "./data", "/vagrant_data"
    machine.vm.provider "virtualbox" do |v|
      v.customize ["modifyvm", :id, "--natdnshostresolver1", "on"]
      v.customize ["modifyvm", :id, "--natdnsproxy1", "on"]
    end
  end
  
  # Run Ansible
  config.vm.define "ansible-ntp" do |define|
    define.vm.hostname = "ansible-ntp"
    define.vm.network :private_network, ip: "10.0.15.10"
    define.vm.synced_folder "./data", "/vagrant_data"
    define.vm.provision "ansible" do |ansible|
      ansible.verbose = "v"
      ansible.limit="ansible-ntp"
      ansible.playbook = "../ansible_ansible_playbook/site.yml"
    end
  end
  
end
