# -*- mode: ruby -*-
# vi: set ft=ruby :

# All Vagrant configuration is done below. The "2" in Vagrant.configure
# configures the configuration version (we support older styles for
# backwards compatibility). Please don't change it unless you know what
# you're doing.
Vagrant.configure(2) do |config|
  # The most common configuration options are documented and commented below.
  # For a complete reference, please see the online documentation at
  # https://docs.vagrantup.com.

  # Every Vagrant development environment requires a box. You can search for
  # boxes at https://atlas.hashicorp.com/search.
  config.vm.box = "centos/7"

  # Proxy settings
  config.proxy.http     = "http://userproxy.visa.com:80"
  config.proxy.https    = "http://userproxy.visa.com:443"
  config.proxy.no_proxy = "localhost,127.0.0.1,127.0.1.1,127.0.1.1*,local.home"
  
  config.vm.define "test-hostmachine" do |machine|
    machine.vm.hostname="test-hostmachine"
    machine.vm.synced_folder "./","/vagrant_ansible"
    machine.vm.network :private_network, ip: "192.168.10.4"

    machine.vm.provision "shell", path:"load_guest_additions.sh"
  end
end
