import java.util.Random

node ('ovn_build') {
  def builder = 'ovn-docker.artifactory.trusted.visa.com/centos7_ovn_docker'
  def mounts = '-v /sys/fs/cgroup:/sys/fs/cgroup -v /home/was/.ssh:/home/was/.ssh'

  try {

    stage('Clone repository') {
      /* Let's make sure we have the repository cloned to our workspace */
      checkout scm
    }

    stage('Deploy CAS_UI in dev2') {
      docker.image("${builder}").inside("${mounts}") {
        sh "chmod 600 config/id_dev"
        sh "ansible-playbook ansible_ovn/deploy_cas_ui.yaml -i config/dev2-nightly.inventory  --extra-vars @config/dev2-nightly.vars.yml -u root --private-key config/id_dev"
      }
    }

    mail body: "cas_ui deployment to dev2 successful" ,
      subject: 'cas_ui deployment to dev2 successful' ,
      to: 'rmore@visa.com'

  } catch (err) {

    mail body: "project build error is here: ${env.BUILD_URL}" ,
      subject: 'cas_ui deployment to dev2 failed.' ,
      to: 'rmore@visa.com'
      
  }
}