# -*- mode: ruby -*-
# vi: set ft=ruby :

# All Vagrant configuration is done below. The "2" in Vagrant.configure
# configures the configuration version (we support older styles for
# backwards compatibility). Please don't change it unless you know what
# you're doing.
Vagrant.configure(2) do |config|
  config.vm.box = "centos/7"
  config.vm.box_version = "1603.01" # use CentOS 7.2 version to match with OVN

  config.proxy.http     = "http://userproxy.visa.com:80"
  config.proxy.https    = "http://userproxy.visa.com:443"
  config.proxy.no_proxy = "localhost,127.0.0.1,127.0.1.1,127.0.1.1*,local.home"
  
  config.vm.define "dmcrypt-hostmachine" do |machine|
    machine.vm.hostname="dmcrypt-hostmachine"
    machine.vm.synced_folder "./","/vagrant_ansible"
    machine.vm.network :private_network, ip: "10.0.15.10"
    machine.vm.provider "virtualbox" do |v|
      v.customize ["modifyvm", :id, "--natdnshostresolver1", "on"]
      v.customize ["modifyvm", :id, "--natdnsproxy1", "on"]
      if ARGV[0] == "up" && ! File.exist?('disk1.vdi')
        v.customize ['createhd',
                     '--filename',
                     'disk1.vdi',
                     '--format', 'VDI',
                     '--size', 10 * 1024]
      end
      v.customize ['storageattach', :id,
                   '--storagectl', 'IDE Controller',
                   '--port', 0, '--device', 1,
                   '--type', 'hdd', '--medium',
                   'disk1.vdi']
    end
    machine.vm.provision "ansible" do |ansible|
      ansible.verbose = "v"
      ansible.limit="dmcrypt-hostmachine"
      ansible.playbook="../../ansible_ovn/cryptsetup.yml"
    end
  end
end
